const defaultLists = [
  {
    name: 'Food',
    words: [
      { eng: 'apple', rus: 'яблоко' },
      { eng: 'meat', rus: 'мясо' },
      { eng: 'water', rus: 'вода' },
      { eng: 'juice', rus: 'сок' },
      { eng: 'tomato', rus: 'помидор' },
      { eng: 'milk', rus: 'молоко' },
      { eng: 'tea', rus: 'чай' },
      { eng: 'coffee', rus: 'кофе' },
      { eng: 'sausage', rus: 'сосиска' },
      { eng: 'cabbage', rus: 'капуста' },
      { eng: 'carrot', rus: 'морковь' },
      { eng: 'cucumber', rus: 'огурец' },
      { eng: 'garlic', rus: 'чеснок' },
      { eng: 'onion', rus: 'лук репчатый' },
      { eng: 'potato', rus: 'картофель' },
      { eng: 'banana', rus: 'банан' },
      { eng: 'cherry', rus: 'вишня' },
      { eng: 'grape', rus: 'виноград' },
      { eng: 'lemon', rus: 'лимон' },
      { eng: 'pear', rus: 'груша' },
      { eng: 'plum', rus: 'слива' },
      { eng: 'strawberry', rus: 'клубника' },
      { eng: 'watermelon', rus: 'арбуз' },
      { eng: 'rice', rus: ' рис' },
      { eng: 'cheese', rus: 'сыр' },
      { eng: 'egg', rus: 'яйцо' },
      { eng: 'cookie', rus: 'печенье' },
      { eng: 'cake', rus: 'торт' },
      { eng: 'sugar', rus: 'сахар' },
      { eng: 'pizza', rus: 'пицца' },
    ],
  },
  {
    name: 'Base verbs',
    words: [
      { eng: 'swim', rus: 'плавать' },
      { eng: 'run', rus: 'бегать' },
      { eng: 'walk', rus: 'ходить' },
      { eng: 'call', rus: 'звонить' },
      { eng: 'open', rus: 'открывать' },
      { eng: 'close', rus: 'закрывать' },
      { eng: 'turn', rus: 'поворачивать' },
      { eng: 'return', rus: 'возвращать' },
      { eng: 'eat', rus: 'есть' },
      { eng: 'drink', rus: 'пить' },
      { eng: 'see', rus: 'видеть' },
      { eng: 'talk', rus: 'говорить' },
      { eng: 'say', rus: 'сказать' },
      { eng: 'tell', rus: 'рассказывать' },
      { eng: 'dance', rus: 'танцевать' },
      { eng: 'listen', rus: 'слушатьe' },
      { eng: 'relax', rus: 'отдыхать' },
      { eng: 'fly', rus: 'летать' },
      { eng: 'sing', rus: 'петь' },
      { eng: 'love', rus: 'любить' },
      { eng: 'like', rus: 'нравиться' },
      { eng: 'want', rus: 'хотеть' },
      { eng: 'think', rus: 'думать' },
      { eng: 'count', rus: 'считать' },
      { eng: 'read', rus: 'читать' },
      { eng: 'write', rus: 'писать' },
      { eng: 'keep', rus: 'держать' },
      { eng: 'kiss', rus: 'целовать' },
      { eng: 'sell', rus: 'продавать' },
      { eng: 'buy', rus: 'покупать' },
    ],
  },
  {
    name: 'Colors',
    words: [
      { eng: 'black', rus: 'черный' },
      { eng: 'red', rus: 'красный' },
      { eng: 'yellow', rus: 'жёлтый' },
      { eng: 'grey', rus: 'серый' },
      { eng: 'white', rus: 'белый' },
      { eng: 'blue', rus: 'синий' },
      { eng: 'pink', rus: 'розовый' },
      { eng: 'green', rus: 'зеленый' },
      { eng: 'orange', rus: 'оранжевый' },
      { eng: 'brawn', rus: 'коричневый' },
      { eng: 'silver', rus: 'серебряный' },
      { eng: 'golden', rus: 'золотой' },
      { eng: 'transparent', rus: 'прозрачный' },
      { eng: 'violet', rus: 'фиолетовый' },
      { eng: 'vinous', rus: 'бордовый' },
      { eng: 'lilac', rus: 'сиреневый' },
      { eng: 'chocolate', rus: 'шоколадный' },
      { eng: 'coral', rus: 'коралловый' },
      { eng: 'raspberry', rus: 'малиновый' },
      { eng: 'pearl', rus: 'жемчужный' },
    ],
  },
  {
    name: 'Animals',
    words: [
      { eng: 'cat', rus: 'кот' },
      { eng: 'dog', rus: 'собака' },
      { eng: 'rabbit', rus: 'кролик' },
      { eng: 'shark', rus: 'акула' },
      { eng: 'fish', rus: 'рыба' },
      { eng: 'parrot', rus: 'попугай' },
      { eng: 'elephant', rus: 'слон' },
      { eng: 'koala', rus: 'коала' },
      { eng: 'kangaroo', rus: 'кенгуру' },
      { eng: 'caw', rus: 'корова' },
      { eng: 'wolf', rus: 'волк' },
      { eng: 'fox', rus: 'лиса' },
      { eng: 'hen', rus: 'курица' },
      { eng: 'lion', rus: 'лев' },
      { eng: 'monkey', rus: 'обезьяна' },
      { eng: 'gull', rus: 'чайка' },
      { eng: 'eagle', rus: 'орел' },
      { eng: 'penguin', rus: 'пингвин' },
      { eng: 'rhino', rus: 'носорог' },
      { eng: 'snake', rus: 'змея' },
      { eng: 'tiger', rus: 'тигр' },
      { eng: 'bear', rus: 'медведь' },
      { eng: 'panda', rus: 'панда' },
      { eng: 'deer', rus: 'олень' },
      { eng: 'bee', rus: 'пчела' },
      { eng: 'giraffe', rus: 'жираф' },
      { eng: 'mouse', rus: 'мышь' },
      { eng: 'rat', rus: 'крыса' },
      { eng: 'hamster', rus: 'хомяк' },
      { eng: 'pig', rus: 'свинья' },
      { eng: 'duck', rus: 'утка' },
      { eng: 'puppy', rus: 'щенок' },
      { eng: 'kitten', rus: 'котенок' },
      { eng: 'bull', rus: 'бык' },
      { eng: 'horse', rus: 'лошадь' },
      { eng: 'sheep', rus: 'овца' },
      { eng: 'hare', rus: 'заяц' },
      { eng: 'squirrel', rus: 'белка' },
      { eng: 'camel', rus: 'верблюд' },
      { eng: 'fly', rus: 'муха' },
      { eng: 'spider', rus: 'паук' },
      { eng: 'scorpion', rus: 'скорпион' },
      { eng: 'beetle', rus: 'жук' },
      { eng: 'crocodile', rus: 'крокодил' },
      { eng: 'turtle', rus: 'черепаха' },
      { eng: 'sparrow', rus: 'воробей' },
      { eng: 'raven', rus: 'ворона' },
      { eng: 'swallow', rus: 'ласточка' },
      { eng: 'dove', rus: 'голубь' },
      { eng: 'swan', rus: 'лебедь' },
    ],
  },
  {
    name: 'Pronouns',
    words: [
      { eng: 'i', rus: 'я' },
      { eng: 'you', rus: 'ты' },
      { eng: 'we', rus: 'мы' },
      { eng: 'he', rus: 'он' },
      { eng: 'she', rus: 'она' },
      { eng: 'it', rus: 'оно' },
      { eng: 'they', rus: 'они' },
      { eng: 'them', rus: 'им' },
      { eng: 'us', rus: 'нас' },
      { eng: 'his', rus: 'его' },
      { eng: 'him', rus: 'ему' },
      { eng: 'her', rus: 'ёё' },
      { eng: 'me', rus: 'мне' },
      { eng: 'those', rus: 'те' },
      { eng: 'these', rus: 'эти' },
      { eng: 'this', rus: 'это' },
      { eng: 'that', rus: 'тот' },
      { eng: 'my', rus: 'мой' },
      { eng: 'your', rus: 'твой' },
      { eng: 'our', rus: 'наш' },
      { eng: 'their', rus: 'их' },
      { eng: 'such', rus: 'такой' },
      { eng: 'self', rus: 'себя' },
      { eng: 'what', rus: 'что' },
      { eng: 'who', rus: 'кто' },
      { eng: 'whom', rus: 'кого' },
      { eng: 'whose', rus: 'чей' },
      { eng: 'which', rus: 'который' },
      { eng: 'when', rus: 'когда' },
      { eng: 'why', rus: 'почему' },
      { eng: 'how', rus: 'как' },
      { eng: 'nothing', rus: 'ничего' },
      { eng: 'nobody', rus: 'никто' },
      { eng: 'none', rus: 'ни один из' },
      { eng: 'neither', rus: 'никто из' },
      { eng: 'nowhere', rus: 'нигде' },
      { eng: 'somebody', rus: 'кто-нибудь' },
      { eng: 'something', rus: 'что-нибудь' },
      { eng: 'anybody', rus: 'кто-угодно' },
      { eng: 'anything', rus: 'что-угодно' },
    ],
  },
];

export default defaultLists;
